name = "print-farm-companion"
compatibility_date = "2024-09-23"
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "printfarmcompanion-db"
database_id = "2c6d79ae-e733-459d-a021-f604d22e59f9"
